openapi: 3.0.3
info:
  title: Calculator Service
  description: HTTP service for adding numbers, a goa teaser
  version: "1.0"
servers:
- url: http://localhost:8000/calc
  description: calc hosts the Calculator Service.
- url: https://v1.goa.design/calc
  description: calc hosts the Calculator Service.
  variables:
    version:
      default: v1
paths:
  /add/{a}/{b}:
    get:
      tags:
      - calc
      summary: add calc
      operationId: calc#add
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        schema:
          type: integer
          description: Left operand
          example: 360622074634248926
          format: int64
        example: 8133055152903002499
      - name: b
        in: path
        description: Right operand
        required: true
        schema:
          type: integer
          description: Right operand
          example: 3219793201326175278
          format: int64
        example: 8803302123552712831
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: integer
                example: 8399553735696626949
                format: int64
              example: 5401762099778430809
  /swagger.json:
    get:
      tags:
      - calc
      summary: Download ../../gen/http/openapi.json
      operationId: calc#/swagger.json
      responses:
        "200":
          description: File downloaded
components: {}
