swagger: "2.0"
info:
  title: Goakit example Calc API
  description: This API demonstrates the use of the goa goakit plugin
  version: ""
host: localhost:8080
paths:
  /add/{a}/{b}:
    get:
      tags:
      - calc
      summary: add calc
      description: Add adds up the two integer parameters and returns the results.
      operationId: calc#add
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        type: integer
      - name: b
        in: path
        description: Right operand
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
